// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkl6s4djKjUtxw4Lsvfvq2boIp3ReDa50',
    appId: '1:802403037206:web:e9f89ee26cffd5d0824537',
    messagingSenderId: '802403037206',
    projectId: 'study-planner-main',
    authDomain: 'study-planner-main.firebaseapp.com',
    storageBucket: 'study-planner-main.firebasestorage.app',
    measurementId: 'G-3ES7VYX21B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc-n76yE30ofj_9z-t5KY62TEKgffY314',
    appId: '1:802403037206:android:74122341d9614f2e824537',
    messagingSenderId: '802403037206',
    projectId: 'study-planner-main',
    storageBucket: 'study-planner-main.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNgjx4UGxn7RqHU9LIFzZ7NajvHHGtAxY',
    appId: '1:802403037206:ios:2f5ecae732322ba6824537',
    messagingSenderId: '802403037206',
    projectId: 'study-planner-main',
    storageBucket: 'study-planner-main.firebasestorage.app',
    iosBundleId: 'com.example.studyPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNgjx4UGxn7RqHU9LIFzZ7NajvHHGtAxY',
    appId: '1:802403037206:ios:2f5ecae732322ba6824537',
    messagingSenderId: '802403037206',
    projectId: 'study-planner-main',
    storageBucket: 'study-planner-main.firebasestorage.app',
    iosBundleId: 'com.example.studyPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkl6s4djKjUtxw4Lsvfvq2boIp3ReDa50',
    appId: '1:802403037206:web:af3460c0c385f138824537',
    messagingSenderId: '802403037206',
    projectId: 'study-planner-main',
    authDomain: 'study-planner-main.firebaseapp.com',
    storageBucket: 'study-planner-main.firebasestorage.app',
    measurementId: 'G-00WRXWPJZD',
  );
}
